#!/bin/bash

if [ -d /Library/Apple ]; then
	# macOS
	[ ! -f /usr/local/bin/brew ] && /bin/bash -c "$(curl -fsSL https://raw.githubusercontent.com/Homebrew/install/master/install.sh)"
	if [ ! -f /opt/homebrew/bin/getopt ]; then
		#[ -d /usr/local/Cellar/awk ] && brew unlink awk
		brew install coreutils diffutils findutils gawk gnu-sed gnu-getopt gnu-tar grep make ncurses pkg-config wget quilt xz gcc@11 sdl2 go
		ln -s /opt/homebrew/Cellar/gnu-getopt/2.40.1/bin/getopt /opt/homebrew/bin
		ln -s /opt/homebrew/Cellar/gnu-sed/4.9/libexec/gnubin/sed /opt/homebrew/bin
		ln -s /opt/homebrew/Cellar/make/4.4.1/libexec/gnubin/make /opt/homebrew/bin
	fi
	[ -f /etc/paths.d/com.vmware.fusion.public ] && sudo rm /etc/paths.d/com.vmware.fusion.public
else
	# Ubuntu 22
	apt update -y
	apt upgrade -y
	apt install build-essential clang flex g++ gawk gettext git libncurses5-dev libssl-dev python3-distutils rsync unzip zlib1g-dev file wget curl
fi

#git clone https://github.com/Yonsm/OponWrt

CDIR=$(cd "${0%/*}"; pwd)
sed -i '/OpenWrt/d' ~/.profile
echo "export PATH=\"$CDIR:\$PATH\"" >> ~/.profile
source ~/.profile
