#!/bin/bash

# Ubuntu 22
apt update -y
apt upgrade -y
apt install build-essential clang flex g++ gawk gettext git libncurses5-dev libssl-dev python3-distutils rsync unzip zlib1g-dev file wget curl

# Debian arm64
# apt install -y ack antlr3 aria2 asciidoc autoconf automake autopoint binutils bison build-essential
# apt install -y bzip2 ccache cmake cpio curl device-tree-compiler fastjar flex gawk gettext
# apt install -y git gperf haveged help2man intltool libelf-dev libglib2.0-dev libgmp3-dev libltdl-dev
# apt install -y libmpc-dev libmpfr-dev libncurses5-dev libncursesw5-dev libreadline-dev libssl-dev libtool lrzsz
# apt install -y mkisofs msmtp nano ninja-build p7zip p7zip-full patch pkgconf python2.7 python3 python3-pip libpython3-dev qemu-utils
# apt install -y rsync scons squashfs-tools subversion swig texinfo uglifyjs upx-ucl unzip vim wget xmlto xxd zlib1g-dev
# apt install g++-multilib-i686-linux-gnu g++-multilib-s390x-linux-gnu g++-multilib-x86-64-linux-gnu g++-multilib-x86-64-linux-gnux32
# apt install libc6-dev-i386-amd64-cross libc6-dev-i386-cross libc6-dev-i386-x32-cross
# apt install golang-go

fi

#git clone https://github.com/Yonsm/OponWrt

CDIR=$(cd "${0%/*}"; pwd)
sed -i '/OpenWrt/d' ~/.profile
echo "export PATH=\"$CDIR:\$PATH\"" >> ~/.profile
source ~/.profile
