#!/bin/bash

git clone -b v24.10.4 https://github.com/openwrt/openwrt
cd openwrt

./scripts/feeds update -a
./scripts/feeds install -a

cd package
git clone https://github.com/jerrykuku/luci-theme-argon.git
#git clone https://github.com/messense/aliyundrive-webdav.git
git clone --depth=1  https://github.com/fw876/helloworld.git
cd ..
