#!/bin/bash
[ $(basename `pwd`) = openwrt ] || [ $(basename `pwd`) = lede ] || cd ${0%/*}/openwrt >/dev/null 2>&1 || cd ${0%/*}/lede || exit

# TODO: Discard fix

git pull
./scripts/feeds update -a
./scripts/feeds install -a

cd package/helloworld
git pull
cd ../..
