#!/bin/bash
[ $(basename `pwd`) = openwrt ] || cd ${0%/*}/openwrt >/dev/null 2>&1 || exit

# TODO: Discard fix

git pull
./scripts/feeds update -a
./scripts/feeds install -a

cd package/helloworld
git pull
cd ../..

cd package/luci-theme-argon
git pull
cd ../..
