#!/bin/bash
[ $(basename `pwd`) = openwrt ] || [ $(basename `pwd`) = lede ] || cd ${0%/*}/openwrt >/dev/null 2>&1 || cd ${0%/*}/lede || exit

# 特定修改
if [ -d package/lean ]; then
	ZHCN=zh-cn
	${0%/*}/4-fix-lean
	FRPC=frp
else
	ZHCN=zh_Hans
	${0%/*}/4-fix-op
	FRPC=frpc

fi
sed -i 's/router:=.*\\/router:=ppp ppp-mod-pppoe odhcp6c odhcpd-ipv6only dnsmasq-full kmod-fs-cifs kmod-nls-utf8 htop iperf3 openssh-sftp-server luci luci-app-commands luci-app-ddns luci-app-uhttpd luci-app-upnp \\/' include/target.mk

# dnsmasq
# sed -i -e 's#PKG_SOURCE:=.*#PKG_SOURCE:=2.89.tar.gz#' \
# 	-e 's#PKG_UPSTREAM_VERSION:=.*#PKG_UPSTREAM_VERSION:=2.89#' \
# 	-e 's#PKG_SOURCE_URL:=.*#PKG_SOURCE_URL:=https://github.com/Yonsm/dnsmasq/archive/refs/tags/#' \
# 	-e 's#PKG_HASH:=.*#PKG_HASH:=cbe5ac69105606b3acdd922b16050a2ade5b2803c8fb2919dda892df1ead0f81#' package/network/services/dnsmasq/Makefile
sed -i 's#procd_add_jail_mount /etc/passwd#procd_add_jail_mount /etc/gfwlist.txt /etc/gfwlist.conf /etc/passwd#' package/network/services/dnsmasq/files/dnsmasq.init

# 内核标记：解决无法安装官方软件包的问题
sed -i "s/grep '/cp \$(TOPDIR)\/.vermagic \$(LINUX_DIR)\/.vermagic\n\t#rep '/" include/kernel-defaults.mk
sed -i 's/$(SCRIPT_DIR)\/kconfig.pl $(LINUX_DIR)\/.config | $(MKHASH) md5/cat $(LINUX_DIR)\/.vermagic/' package/kernel/linux/Makefile

# 版本标识
sed -i 's/%D %V %C/%D %V/' package/base-files/files/etc/openwrt_release
sed -i 's/LuCI - Lua Configuration Interface/Loading.../' feeds/luci/modules/luci-base/root/www/index.html
sed -i 's#downloads.openwrt.org#mirrors.tencent.com/openwrt#' include/version.mk
#sed -i "s|https.*/OpenWrt|https://github.com/Yonsm/OpenWrt|g" package/luci-app-amlogic/luci-app-amlogic/root/etc/config/amlogic

sed -i 's#DEVICE_COMPAT_VERSION := .*#DEVICE_COMPAT_VERSION := 1.0#' target/linux/ramips/image/mt7621.mk

# 默认配置
sed -i '/sequential_ip/d' package/network/services/dnsmasq/files/dhcp.conf
sed -i 's/config dnsmasq/config dnsmasq\n\toption sequential_ip\t1/' package/network/services/dnsmasq/files/dhcp.conf

sed -i -e 's/users" ] \&\& printf.*/users" ] \&\& (([ "$guest_ok" == "yes" ] \&\& [ "$read_only" == "no" ]) \&\& printf "\\twrite list = %s\\n" "\$users" || printf "\\tvalid users = %s\\n" "\$users")/' \
	-e 's/read_only" ] \&\& printf/read_only" ] \&\& ([ -z "$users" ] ||  [ "$guest_ok" == "no" ] || [ "$read_only" == "yes" ]) \&\& printf/' feeds/packages/net/samba4/files/samba.init
sed -i 's/Samba on OpenWRT/Stroage/' feeds/packages/net/samba4/files/samba.config
sed -i 's/Samba on OpenWrt/Stroage/' feeds/packages/net/samba4/files/samba.init
# sed -i -e 's/################ Filesystem and creation rules ################/\t# Filesystem and creation rules/' \
# 	-e 's#._.DS_Store#._*/lost+found#' \
# 	-e 's/################################################################/\n\taccess based share enum = yes/' feeds/packages/net/samba4/files/smb.conf.template

sed -i -e 's/users" ] \&\& printf.*/users" ] \&\& (([ "$guest_ok" == "yes" ] \&\& [ "$read_only" == "no" ]) \&\& printf "\\read list = guest\\n\\twrite list = %s\\n" "\$users" || printf "\\tvalid users = %s\\n" "\$users")/' \
	-e 's/read_only" ] \&\& printf/read_only" ] \&\& ([ -z "$users" ] ||  [ "$guest_ok" == "no" ] || [ "$read_only" == "yes" ]) \&\& printf/' feeds/packages/net/ksmbd-tools/files/ksmbd.init
sed -i 's/Ksmbd on OpenWrt/Stroage/' feeds/packages/net/ksmbd-tools/files/ksmbd.config
sed -i 's/Ksmbd on OpenWrt/Stroage/' feeds/packages/net/ksmbd-tools/files/ksmbd.config.example
sed -i -e 's/\tsmb2 max/\t#smb2 max/' \
	-e 's#\tcache read buffers#\tveto files = /Thumbs.db/.DS_Store/._*/.apdisk/lost+found/\n\t\#cache read buffers#' \
	-e 's/\tcache trans buffers/\t#cache trans buffers/' feeds/packages/net/ksmbd-tools/files/ksmbd.conf.template

sed -i -e 's/disabled=1/disabled=0/' -e 's/ssid=.*/ssid=Router`[ $devidx != 1 ] \&\& echo $devidx`/' package/kernel/mac80211/files/lib/wifi/mac80211.sh
sed -i 's_root:::_root:$1$iG/alp.I$UezVYUU8eoLfjQ1grCHsx/:19448:_' package/base-files/files/etc/shadow

# 你好世界：去除 XRay@go，选择 Trojan@cpp
sed -i 's/y if i386||x86_64||arm/n/' package/helloworld/luci-app-ssr-plus/Makefile
sed -i 's/if aarch64||arm||i386||x86_64/if aarch64_no||arm_no||i386_no||x86_64_no/' package/helloworld/luci-app-ssr-plus/Makefile
sed -i ':a;N;s/default n\nendef/default y\nendef/;$!ba' package/helloworld/luci-app-ssr-plus/Makefile
#sed -i 's/Shadowsocks New Version/Shadowsocks/' package/helloworld/luci-app-ssr-plus/luasrc/model/cbi/shadowsocksr/client-config.lua
sed -i 's/=+libev/=+libopenssl-legacy +libev/' package/helloworld/shadowsocksr-libev/Makefile

# 防火墙：开启 HTTPS 端口
sed -i 's/:443/:81/'  package/network/services/uhttpd/files/uhttpd.config
[ ! -f  package/network/config/firewall4/firewall.config ] && curl -o package/network/config/firewall4/firewall.config "https://git.openwrt.org/?p=project/firewall4.git;a=blob_plain;f=root/etc/config/firewall"
grep INSTALL_CONF package/network/config/firewall4/Makefile || sed -i 's#(1)/#(1)/\n\t$(INSTALL_CONF) ./firewall.config $(1)/etc/config/firewall#' package/network/config/firewall4/Makefile
for FILE in package/network/config/firewall/files/firewall.config package/network/config/firewall4/firewall.config; do
grep Allow-HTTPS $FILE || cat <<\EOF >>$FILE

config rule
	option name		Allow-HTTPS
	option src		wan
	option proto		tcp
	option dest_port	81
	option target		ACCEPT
EOF
done

# 文案调整
sed -i -e 's/"ShadowSocksR Plus+ 设置"/"科学上网设置"\n\nmsgid "ShadowSocksR Plus+"\nmsgstr "科学上网"/' -e 's/shadowsocks rust版本/Shadowsocks/' package/helloworld/luci-app-ssr-plus/po/zh-cn/ssr-plus.po

sed -i 's/msgstr "Docker"/msgstr "容器"/' feeds/luci/applications/luci-app-dockerman/po/$ZHCN/dockerman.po
sed -i 's/msgstr "存储卷"/msgstr "存储"/' feeds/luci/applications/luci-app-dockerman/po/$ZHCN/dockerman.po

sed -i 's/"frp 服务器"/"公网穿透"/' feeds/luci/applications/luci-app-frps/po/$ZHCN/frps.po
sed -i 's/"frp 客户端"/"内网穿透"/' feeds/luci/applications/luci-app-frpc/po/$ZHCN/$FRPC.po
#sed -i 's/msgstr "Reverse proxy"/msgstr "内网穿透"/' feeds/luci/applications/luci-app-xfrpc/po/zh_Hans/frpc.po

sed -i 's/msgstr "UPnP"/msgstr "端口映射"/' feeds/luci/applications/luci-app-upnp/po/$ZHCN/upnp.po
sed -i 's/自定义命令/自定命令/' feeds/luci/applications/luci-app-commands/po/$ZHCN/commands.po
sed -i 's/msgstr "uHTTPd"/msgstr "网页服务"/' feeds/luci/applications/luci-app-uhttpd/po/$ZHCN/uhttpd.po
sed -i 's/msgstr "Transmission"/msgstr "比特传输"/' feeds/luci/applications/luci-app-transmission/po/$ZHCN/transmission.po
sed -i 's/"WiFi 计划"/"无线计划"/' feeds/luci/applications/luci-app-wifischedule/po/$ZHCN/wifischedule.po

sed -i -e 's/允许匿名用户/访客/' \
	-e 's/Apple Time-machine 共享/时间机器/' \
	-e 's/创建权限掩码/创建掩码/' \
	-e 's/目录权限掩码/目录掩码/' \
	-e 's/禁用 Netbios/禁用 NetBIOS/' \
	-e 's/禁用 Winbind/WinBind/' \
	-e 's/编辑用来生成 samba 设置的模板。/编辑用来生成 Samba 设置的模板/' \
	-e 's/启用 macOS 兼容共享/兼容 macOS 特性/' \
	-e 's/仅来宾用户/仅访客/' \
	-e 's/继承所有者/继承权限/' \
	-e 's/Time-machine 大小（GB）/机器大小/' \
	-e 's/可浏览/浏览/' \
	-e 's/VFS 对象/虚拟对象/' \
	-e 's/继承权限/继承/' \
	-e 's/强制 Root/强根/' \
	-e 's/"目录"/"共享目录路径"/' \
	-e 's/"名称"/"共享目录名称"/' \
    feeds/luci/applications/luci-app-samba4/po/$ZHCN/samba4.po

sed -i ':a;N;s/msgid "Mount Points"\nmsgstr "挂载点"/msgid "Mount Points"\nmsgstr "挂载位置"/;$!ba' feeds/luci/modules/luci-base/po/$ZHCN/base.po
sed -i ':a;N;s/msgid "Reboot"\nmsgstr "重启"/msgid "Reboot"\nmsgstr "重新启动"/;$!ba' feeds/luci/modules/luci-base/po/$ZHCN/base.po
sed -i 's/DHCP\/DNS/主机域名/' feeds/luci/modules/luci-base/po/$ZHCN/base.po
#sed -i 's/"无线"/"无线网络"/' feeds/luci/modules/luci-base/po/$ZHCN/base.po

sed -i -e 's/阿里云盘 WebDAV/阿里云盘/' -e 's/msgstr "Refresh Token"/msgstr "刷新令牌"/' -e 's/(bytes)/（字节）/' -e 's/单位为//' -e 's/云盘驱动类型/云盘类型/' -e 's/：resource, backup/：资源盘、备份盘/' feeds/luci/applications/luci-app-aliyundrive-webdav/po/zh-cn/aliyundrive-webdav.po

# 清理 macOS 文件和错误
sed -i "s/'CVS' -o -name '.svn'/'CVS' -o -name '.DS_Store' -o -name '.svn'/" include/package-ipkg.mk

# 文件修改
cp -r ${0%/*}/fix-files/* .
