#!/bin/bash
[ $(basename `pwd`) = openwrt ] || [ $(basename `pwd`) = lede ] || cd ${0%/*}/openwrt >/dev/null 2>&1 || cd ${0%/*}/lede || exit

# 默认软件包
sed -i -e 's/dnsmasq-full firewall.*\\/firewall iptables \\/' \
	-e 's/block-mount coremark.*/coremark \\/' \
	-e 's/iptables-mod-tproxy.*/luci-proto-ipv6 \\/' \
	-e 's/ddns-scripts_aliyun.*/ddns-scripts_dnspod \\/' \
	-e 's/luci-app-arpbind.*/luci-theme-argon-mod \\/' \
	-e 's/luci-app-accesscontrol luci-app-nlbwmon luci-app-turboacc luci-app-wol //' include/target.mk

# 版本
sed -i 's/%D %V %C/%D Master/' package/base-files/files/etc/openwrt_release
sed -i 's/%R/R23/' package/base-files/files/etc/openwrt_release
sed -i 's#openwrt/luci#Yonsm#' feeds/luci/themes/luci-theme-argon-mod/luasrc/view/themes/argon/footer.htm
sed -i -e 's/${2:-Git}/$(date +%Y-%m-%d)/' -e 's/${3:-LuCI}/Yonsm/' feeds/luci/modules/luci-base/src/mkversion.sh

#  默认设置
sed -i '/option Interface/d' package/network/services/dropbear/files/dropbear.config
sed -i 's/encryption=none/encryption=psk2\n\t\t\tset wireless.default_radio${devidx}.key=asdfqwer/' package/kernel/mac80211/files/lib/wifi/mac80211.sh

# 菜单调整
sed -i 's/"services"/"nas"/g' feeds/luci/applications/luci-app-aria2/luasrc/controller/aria2.lua
sed -i 's/services/nas/' feeds/luci/applications/luci-app-aria2/luasrc/view/aria2/overview_status.htm
sed -i 's/"services"/"nas"/g' feeds/luci/applications/luci-app-hd-idle/luasrc/controller/hd_idle.lua
sed -i 's/"services"/"nas"/g' feeds/luci/applications/luci-app-samba/luasrc/controller/samba.lua
sed -i 's/"services"/"nas"/g' feeds/luci/applications/luci-app-samba4/luasrc/controller/samba4.lua
#sed -i 's/"services"/"nas"/g' feeds/luci/applications/luci-app-transmission/luasrc/controller/transmission.lua
#sed -i 's/"services"/"network"/g' feeds/luci/applications/luci-app-wifischedule/luasrc/controller/wifischedule/wifi_schedule.lua

sed -i 's/"services"/"nas"/g' feeds/luci/applications/luci-app-aliyundrive-fuse/luasrc/controller/aliyundrive-fuse.lua
sed -i 's/"services"/"nas"/g' feeds/luci/applications/luci-app-aliyundrive-webdav/luasrc/controller/aliyundrive-webdav.lua

sed -i 's/"system"/"nas"/g' feeds/luci/applications/luci-app-diskman/luasrc/controller/diskman.lua
sed -i 's/system\/diskman/nas\/diskman/g' feeds/luci/applications/luci-app-diskman/luasrc/view/diskman/disk_info.htm
sed -i 's/system\/diskman/nas\/diskman/g' feeds/luci/applications/luci-app-diskman/luasrc/view/diskman/partition_info.htm
sed -i 's/"system"/"nas"/' feeds/luci/applications/luci-app-diskman/luasrc/view/diskman/smart_detail.htm
sed -i 's/system\/diskman/nas\/diskman/g' feeds/luci/applications/luci-app-diskman/luasrc/model/cbi/diskman/btrfs.lua
sed -i 's/system\/diskman/nas\/diskman/g' feeds/luci/applications/luci-app-diskman/luasrc/model/cbi/diskman/disks.lua
sed -i 's/system\/diskman/nas\/diskman/g' feeds/luci/applications/luci-app-diskman/luasrc/model/cbi/diskman/partition.lua

# 文案
sed -i 's/"动态 DNS"/"动态域名"/' feeds/luci/applications/luci-app-ddns/po/zh-cn/ddns.po

sed -i 's/<abbr title=\\"Light Emitting Diode\\">LED<\/abbr> 配置/灯光配置/' feeds/luci/modules/luci-base/po/zh-cn/base.po
sed -i ':a;N;s/msgid "Hostnames"\nmsgstr "主机名"/msgid "Hostnames"\nmsgstr "主机名称"/;$!ba' feeds/luci/modules/luci-base/po/zh-cn/base.po
sed -i 's/备份\/升级/备份升级/' feeds/luci/modules/luci-base/po/zh-cn/base.po

sed -i -e 's/"防火墙"/"防火长城"/' -e 's/"Firewall"/"Firewalls"/' feeds/luci/applications/luci-app-firewall/po/zh-cn/firewall.po
sed -i 's/"Firewall"/"Firewalls"/' feeds/luci/applications/luci-app-firewall/luasrc/controller/firewall.lua
sed -i 's/Aria2 配置/下载工具/' feeds/luci/applications/luci-app-aria2/po/zh-cn/aria2.po
sed -i 's/TTYD 终端/仿终端/' feeds/luci/applications/luci-app-ttyd/po/zh-cn/terminal.po

sed -i 's/"CPU 性能优化调节"/"性能调节"/' feeds/luci/applications/luci-app-cpufreq/po/zh-cn/cpufreq.po
sed -i "s/Argon 主题设置/主题设置/" feeds/luci/applications/luci-app-argon-config/po/zh-cn/argon-config.po
sed -i 's/Turbo ACC 网络加速/网络加速/' feeds/luci/applications/luci-app-turboacc/po/zh-cn/turboacc.po

sed -i 's/挂载 SMB 网络共享/挂载共享/' feeds/luci/applications/luci-app-cifs-mount/po/zh-cn/cifs.po
sed -i 's/)).dependent/), 8).dependent/' feeds/luci/applications/luci-app-cifs-mount/luasrc/controller/cifs.lua
sed -i -e 's/阿里云盘 FUSE/阿里网盘/' -e 's/msgstr "Refresh Token"/msgstr "刷新令牌"/'  -e 's/,10//' feeds/luci/applications/luci-app-aliyundrive-fuse/po/zh-cn/aliyundrive-fuse.po

sed -i ':a;N;s/y\n		select PACKAGE_kmod-macvlan/n\n		select PACKAGE_kmod-macvlan/;$!ba' feeds/packages/utils/dockerd/Config.in

grep 专网 feeds/luci/modules/luci-base/po/zh-cn/base.po || cat <<\EOF >> feeds/luci/modules/luci-base/po/zh-cn/base.po

msgid "NAS"
msgstr "存储"

msgid "VPN"
msgstr "专网"
EOF
