#!/bin/bash
[ $(basename `pwd`) = openwrt ] || cd ${0%/*}/openwrt >/dev/null 2>&1 || exit

if [ ! -z $1 ]; then
	CONFIG=${0%/*}/config/.config.$1;
	ln -sf $CONFIG .config

	USB=1
	MODTOOL=0
	case "$1" in
	CM520*)
		MAGIC=b5ab1d6f6247c989eccb311be6c450fd
		BOARD=ipq40xx
		TARGET=generic
		DEVICE=DEVICE_mobipromo_cm520-79f
		;;
	K2P*|C5*|NEWIFI3*)
		MAGIC=9c242f353867f49a96054ff8c9f2c460
		BOARD=ramips
		TARGET=mt7621
		case "$1" in
			K2P*) DEVICE=DEVICE_phicomm_k2p; [[ $1 != *\+USB* ]] && USB=0;;
			C5*) DEVICE=DEVICE_xiaoyu_xy-c5;;
			NEWIFI3*) DEVICE=DEVICE_d-team_newifi-d2;;
		esac
		;;
	Y1*)
		MAGIC=0e8896b32ade622c6f0cbd83ee589109
		BOARD=ramips
		TARGET=mt7620
		DEVICE=DEVICE_lenovo_newifi-y1
		;;
	RMAX6000*)
		MAGIC=88bbb0b8c80abf953ee5e7001a2ef514
		BOARD=mediatek
		TARGET=filogic
		[ $1 == RMAX6000+STOCK ] && DEVICE=DEVICE_xiaomi_redmi-router-ax6000-stock || DEVICE=DEVICE_xiaomi_redmi-router-ax6000
		USB=0
		;;
	N1*)
		MAGIC=2aca45916f439a8d3636bae83bbaeef5
		BOARD=armsr
		TARGET=armv8
		DEVICE=generic
		MODTOOL=1
		;;
	X64*)
		MAGIC=e496746edd89318b9810e48e36a8bd9c
		BOARD=x86
		TARGET=64
		DEVICE=DEVICE_generic
		MODTOOL=1
		;;
	*)
		MAGIC=00000000000000000000000000000000
		DEVICE=
		[[ $1 != *\+USB* ]] && USB=0
		;;
	esac

	VERMAGIC=.vermagic.${BOARD}_${TARGET}
	[ ! -f $VERMAGIC ] && echo $MAGIC > $VERMAGIC
	ln -sf $VERMAGIC .vermagic

	if [ ! -f $CONFIG ] || [ "$2" == "-f" ]; then
		cat <<EOF > $CONFIG
# CONFIG_PACKAGE_mkf2fs is not set
CONFIG_BUSYBOX_CUSTOM=y
CONFIG_BUSYBOX_CONFIG_LSOF=y
CONFIG_BUSYBOX_CONFIG_TELNET=y
CONFIG_GOLANG_EXTERNAL_BOOTSTRAP_ROOT="/usr/bin/go"
EOF

		[ ! -z $DEVICE ] && cat <<EOF >> $CONFIG
CONFIG_TARGET_${BOARD}=y
CONFIG_TARGET_${BOARD}_${TARGET}=y
CONFIG_TARGET_${BOARD}_${TARGET}_${DEVICE}=y
EOF

		[ $USB == 1 ] && cat <<EOF >> $CONFIG
CONFIG_BUSYBOX_CONFIG_BLKID=y
CONFIG_BUSYBOX_CONFIG_FEATURE_BLKID_TYPE=y
CONFIG_BUSYBOX_CONFIG_EJECT=y
CONFIG_BUSYBOX_CONFIG_FDISK=y
CONFIG_BUSYBOX_CONFIG_FEATURE_FDISK_WRITABLE=y
CONFIG_BUSYBOX_CONFIG_FEATURE_GPT_LABEL=y
CONFIG_BUSYBOX_CONFIG_FEATURE_FDISK_ADVANCED=y
CONFIG_BUSYBOX_CONFIG_FSCK=y
CONFIG_BUSYBOX_CONFIG_HDPARM=y
CONFIG_BUSYBOX_CONFIG_LOSETUP=y
CONFIG_BUSYBOX_CONFIG_LSUSB=y
CONFIG_BUSYBOX_CONFIG_MKFS_EXT2=y
CONFIG_BUSYBOX_CONFIG_MKFS_VFAT=y
CONFIG_BUSYBOX_CONFIG_TUNE2FS=y
CONFIG_PACKAGE_block-mount=y
CONFIG_PACKAGE_kmod-fs-exfat=y
CONFIG_PACKAGE_kmod-fs-ext4=y
CONFIG_PACKAGE_kmod-fs-ntfs3=y
CONFIG_PACKAGE_kmod-fs-vfat=y
CONFIG_PACKAGE_kmod-nls-cp936=y
CONFIG_PACKAGE_kmod-usb-storage=y
CONFIG_PACKAGE_luci-app-aria2=y
CONFIG_PACKAGE_luci-app-hd-idle=y
CONFIG_PACKAGE_ariang=y
CONFIG_PACKAGE_resize2fs=y
CONFIG_PACKAGE_gdisk=y
EOF

		[[ $1 != *\+NOWING* ]] && echo "CONFIG_PACKAGE_wing=y" >> $CONFIG
		#[ $USB == 1 ] && [ "$DEVICE" != "DEVICE_lenovo_newifi-y1" ] && echo "CONFIG_PACKAGE_luci-app-aliyundrive-webdav=y" >> $CONFIG

		[ $MODTOOL == 1 ] && cat <<EOF >> $CONFIG
CONFIG_BUSYBOX_CONFIG_DEPMOD=y
CONFIG_BUSYBOX_CONFIG_INSMOD=y
CONFIG_BUSYBOX_CONFIG_LSMOD=y
CONFIG_BUSYBOX_CONFIG_FEATURE_LSMOD_PRETTY_2_6_OUTPUT=y
CONFIG_BUSYBOX_CONFIG_MODINFO=y
CONFIG_BUSYBOX_CONFIG_MODPROBE=y
CONFIG_BUSYBOX_CONFIG_RMMOD=y
EOF

		if [[ $1 = *\+SMB4* ]] || [[ $1 = N1* ]] || [[ $1 = X64* ]]; then
			echo "CONFIG_PACKAGE_luci-app-samba4=y" >> $CONFIG
		else
			echo "CONFIG_PACKAGE_luci-app-ksmbd=y" >> $CONFIG
			echo "CONFIG_PACKAGE_ksmbd-avahi-service=y" >> $CONFIG
		fi

		[[ $1 = *\+HASS* ]] && cat <<EOF >> $CONFIG
CONFIG_PACKAGE_mosquitto-client-nossl=y
CONFIG_PACKAGE_mosquitto-nossl=y
CONFIG_PACKAGE_python3-pip=y
CONFIG_PACKAGE_python3-dev=y
CONFIG_PACKAGE_libffi=y
CONFIG_PACKAGE_gcc=y
CONFIG_PACKAGE_ffmpeg=y
EOF
# CONFIG_PACKAGE_python3-cffi=y

		[[ $1 = *\+DOCKER* ]] && cat <<EOF >> $CONFIG
CONFIG_PACKAGE_luci-app-dockerman=y
CONFIG_PACKAGE_dockerd=y
EOF

		[[ $1 = *\+DOCKER* ]] && [[ $1 = X64* ]] && cat <<EOF >> $CONFIG
CONFIG_PACKAGE_kmod-macvlan=y
CONFIG_PACKAGE_kmod-dummy=y
EOF

		[[ $1 = N1* ]] && cat <<EOF >> $CONFIG
# CONFIG_TARGET_ROOTFS_CPIOGZ is not set
# CONFIG_TARGET_ROOTFS_EXT4FS is not set
# CONFIG_TARGET_ROOTFS_SQUASHFS is not set
# CONFIG_DEFAULT_mtd is not set
CONFIG_BRCMFMAC_SDIO=y
# CONFIG_BRCMFMAC_USB is not set
# CONFIG_BRCMFMAC_PCIE is not set
CONFIG_PACKAGE_kmod-usb-net=y
CONFIG_PACKAGE_kmod-brcmfmac=y
CONFIG_PACKAGE_kmod-mac80211=y
CONFIG_PACKAGE_wpa-cli=y
CONFIG_PACKAGE_wpad-basic=y
CONFIG_PACKAGE_kmod-usb2=y
EOF
#CONFIG_PACKAGE_kmod-mt76x0u=y
#CONFIG_BTRFS_PROGS_ZSTD=y
#CONFIG_PACKAGE_btrfs-progs=y

		[[ $1 = X64* ]] && cat <<EOF >> $CONFIG
CONFIG_BUSYBOX_CONFIG_LSPCI=y
CONFIG_TARGET_ROOTFS_TARGZ=y
# CONFIG_TARGET_ROOTFS_SQUASHFS is not set
# CONFIG_GRUB_IMAGES is not set
# CONFIG_PACKAGE_mtd is not set
CONFIG_GRUB_TIMEOUT="2"
CONFIG_TARGET_ROOTFS_PARTSIZE=400
# CONFIG_PACKAGE_kmod-amazon-ena is not set
# CONFIG_PACKAGE_kmod-amd-xgbe is not set
# CONFIG_PACKAGE_kmod-bnx2 is not set
CONFIG_PACKAGE_kmod-e1000=y
# CONFIG_PACKAGE_kmod-e1000e is not set
# CONFIG_PACKAGE_kmod-forcedeth is not set
# CONFIG_PACKAGE_kmod-igb is not set
CONFIG_PACKAGE_kmod-igc=y
# CONFIG_PACKAGE_kmod-ixgbe is not set
# CONFIG_PACKAGE_kmod-phy-realtek is not set
# CONFIG_PACKAGE_kmod-r8169 is not set
# CONFIG_PACKAGE_kmod-tg3 is not set
CONFIG_PACKAGE_lm-sensors=y
CONFIG_PACKAGE_ethtool=y
CONFIG_PACKAGE_kmod-fs-hfsplus=y
CONFIG_PACKAGE_openssl-util=y
CONFIG_PACKAGE_kmod-usb2=y
CONFIG_PACKAGE_kmod-usb3=y
EOF

		[[ $1 = X64* ]] && [[ $1 = *\+WIFI* ]] && cat <<EOF >> $CONFIG
CONFIG_PACKAGE_hostapd=y
CONFIG_PACKAGE_kmod-mac80211=y
CONFIG_PACKAGE_wireless-regdb=y
CONFIG_PACKAGE_wireless-tools=y
CONFIG_PACKAGE_wpa-supplicant=y
CONFIG_PACKAGE_iwlwifi-firmware-ax210=y
CONFIG_PACKAGE_kmod-iwlwifi=y
CONFIG_PACKAGE_kmod-mt76x0u=y
EOF
# CONFIG_PACKAGE_rtl8821ce-firmware=y
# CONFIG_PACKAGE_kmod-rtw88=y
# CONFIG_PACKAGE_pciutils=y
# CONFIG_PACKAGE_wpa-cli=y
# CONFIG_PACKAGE_wpad-basic=y
	fi

	rm -rf files
	[[ $1 = N1* ]] && ln -sf ${0%/*}/n1-files files
fi

cat $CONFIG
make menuconfig
