#!/bin/sh
[ ! -f /boot/uEnv.txt ] && (echo "/boot/uEnv.txt not found"; exit 1)

if grep 'EMMC_ROOTFS2' /boot/uEnv.txt > /dev/null; then
	ROOT=EMMC_ROOTFS1
else
	ROOT=EMMC_ROOTFS2
fi
sed -i "s/root=.* rootfs/root=LABEL=\"$ROOT\" rootfs/" /boot/uEnv.txt
echo Boot to $ROOT
reboot
